### ISSUE TITLE
Delay before stream starts

### ISSUE THREAD

**Issue by WebMaestroFr** [WebMaestroFr/rpi-mpeg-ts#1]
I don't know why yet, but there is a big delay on `npm start` for the conversion to start. Or maybe it's the capture that is late...

**Comment by WebMaestroFr** [comment]
It is apparently the `avconv` process that doesn't output directly...

**Comment by phoboslab** [comment]
avconv probably waits for the first H264 intra frame from raspivid before it can start transcoding. You could try reducing the picture group size (`--intra, -g`) for raspivid. This will increase the data rate, but since it's all local, it shouldn't matter much.

Note that JSMpeg on the client also waits for the first MPEG1 intra frame before it displays anything. I.e. the time until you see the stream on the website is at maximum the intra frame rate that avconv puts out.

**Comment by WebMaestroFr** [comment]
Thanks for the tip @phoboslab, and let me congratulate you for JSMpeg I think it's brilliant.

I just tested with a GOP size equal to the framerate (so one group per second I expect), but still it takes a good minute (if not a couple) to start...

Here the two piped commands (with the GOP options on both outputs) flattened :
```bash
raspivid --nopreview --verbose --hflip --vflip --inline --timeout 0 --framerate 24 --width 640 --height 480 --bitrate 1048576 --intra 24 --output -
|
avconv -fflags nobuffer -f h264 -r 24 -i - -an -f mpegts -codec:v mpeg1video -b:v 1048576 -g 24 -bf 0 -qmin 3 -
```

And it's most probably `avconv` that delays the output. There is data out of `raspivid` almost instantly, and _JSMpeg_ works as soon as the websocket emits data.

**Comment by WebMaestroFr** [comment]
After playing with a few options, it appears that `-probesize` is the answer to this issue.

I'm very new to video streams and [this is not really documented](https://libav.org/documentation/avconv.html#Format-AVOptions)... but for what I understand, `avconv` must be using a big first chunk of the input to gather info about the source, and only then starts outputting. So by decreasing the "probing size", I output almost instantly.

Closing this repo' first issue !
